### ISSUE TITLE
logback 적용,  log & crash 적용

### ISSUE THREAD

**Issue by seung-gyu-kim** [nhnacademy-be5-staff99/store99-bookstore#31]
로깅
https://www.nhncloud.com/kr/service/data-analytics/log-crash-search

**Comment by yrrho2** [comment]
모든서버에 적용완료했습니다.
개발은 console만 출력.
배포는 console과 nhn log&crash로 출력됩니다.

**Comment by yrrho2** [comment]
모든서버에 적용완료했습니다.
개발은 console만 출력.
배포는 console과 nhn log&crash로 출력됩니다.
